brew update

brew upgrade --all
brew install adns
brew install autoconf
brew install automake
brew install awscli
brew install bash-completion
brew install bdw-gc
brew install bison
brew install boost
brew install c-ares
brew install cairo
brew install check
brew install clingo
brew install cmake
brew install coreutils
brew install ctags
brew install docker-machine
brew install docker-machine-driver-xhyve
brew install doxygen
brew install erlang
brew install ethereum
brew install exiftool
brew install findutils
brew install fontconfig
brew install freeimage
brew install freetype
brew install fribidi
brew install fzf
brew install gd
brew install gdbm
brew install geckodriver
brew install gettext
brew install ghostscript
brew install giflib
brew install git
brew install glances
brew install glib
brew install gmp
brew install gnu-sed
brew install gnu-tar
brew install gnu-which
brew install gnupg
brew install gnutls
brew install go
brew install gobject-introspection
brew install gotop
brew install graphite2
brew install graphviz
brew install gts
brew install guile
brew install gx
brew install gx-go
brew install haproxy
brew install harfbuzz
brew install heroku
brew install heroku-node
brew install icu4c
brew install ilmbase
brew install imagemagick@6
brew install ipfs
brew install jansson
brew install jasper
brew install jemalloc
brew install jpeg
brew install json-c
brew install kops
brew install krb5
brew install kubernetes-cli
brew install libassuan
brew install libev
brew install libevent
brew install libffi
brew install libgcrypt
brew install libgpg-error
brew install libidn2
brew install libksba
brew install liblqr
brew install libmaxminddb
brew install libpng
brew install libscrypt
brew install libsmi
brew install libsodium
brew install libspiro
brew install libssh
brew install libtasn1
brew install libtiff
brew install libtool
brew install libuninameslist
brew install libunistring
brew install libusb
brew install libusb-compat
brew install libyaml
brew install libyubikey
brew install little-cms
brew install little-cms2
brew install llvm
brew install llvm@6
brew install lua
brew install lua@5.1
brew install lz4
brew install lzo
brew install ncurses
brew install netpbm
brew install nettle
brew install nghttp2
brew install node
brew install npth
brew install nspr
brew install nss
brew install ocaml
brew install ocamlbuild
brew install opam
brew install openexr
brew install openjdk
brew install openjpeg
brew install openssl@1.1
brew install p11-kit
brew install packer
brew install pam_yubico
brew install pango
brew install pcre
brew install pcre2
brew install pcsc-lite
brew install pinentry
brew install pinentry-mac
brew install pixman
brew install pkg-config
brew install poppler
brew install popt
brew install privoxy
brew install pth
brew install pyenv
brew install python@3.8
brew install qt
brew install rabbitmq
brew install rbenv
brew install rbenv-gemset
brew install readline
brew install redis
brew install rsync
brew install ruby-build
brew install sqlite
brew install ssh-copy-id
brew install sshfs
brew install terraform
brew install thrift
brew install tmux
brew install unbound
brew install utf8proc
brew install watchman
brew install webp
brew install wget
brew install wireshark
brew install wxmac
brew install xhyve
brew install xxhash
brew install xz
brew install yarn
brew install ykclient
brew install ykpers
brew install yubico-piv-tool
brew install zlib
brew install zookeeper
brew install zsh
brew install zstd
brew install adns
brew install autoconf
brew install automake
brew install awscli
brew install bash-completion
brew install bdw-gc
brew install bison
brew install boost
brew install c-ares
brew install cairo
brew install check
brew install clingo
brew install cmake
brew install coreutils
brew install ctags
brew install docker
brew install docker-compose
brew install docker-machine
brew install docker-machine-driver-xhyve
brew install doxygen
brew install erlang
brew install ethereum
brew install exiftool
brew install findutils
brew install fontconfig
brew install freeimage
brew install freetype
brew install fribidi
brew install fzf
brew install gd
brew install gdbm
brew install geckodriver
brew install gettext
brew install ghostscript
brew install giflib
brew install git
brew install glances
brew install glib
brew install gmp
brew install gnu-sed
brew install gnu-tar
brew install gnu-which
brew install gnupg
brew install gnutls
brew install go
brew install gobject-introspection
brew install gotop
brew install graphite2
brew install graphviz
brew install gts
brew install guile
brew install gx
brew install gx-go
brew install haproxy
brew install harfbuzz
brew install heroku
brew install heroku-node
brew install icu4c
brew install ilmbase
brew install imagemagick@6
brew install ipfs
brew install jansson
brew install jasper
brew install jemalloc
brew install jpeg
brew install json-c
brew install kops
brew install krb5
brew install kubernetes-cli
brew install libassuan
brew install libev
brew install libevent
brew install libffi
brew install libgcrypt
brew install libgpg-error
brew install libidn2
brew install libksba
brew install liblqr
brew install libmaxminddb
brew install libpng
brew install libscrypt
brew install libsmi
brew install libsodium
brew install libspiro
brew install libssh
brew install libtasn1
brew install libtiff
brew install libtool
brew install libuninameslist
brew install libunistring
brew install libusb
brew install libusb-compat
brew install libyaml
brew install libyubikey
brew install little-cms
brew install little-cms2
brew install llvm
brew install llvm@6
brew install lua
brew install lua@5.1
brew install lz4
brew install lzo
brew install ncurses
brew install netpbm
brew install nettle
brew install nghttp2
brew install node
brew install npth
brew install nspr
brew install nss
brew install ocaml
brew install ocamlbuild
brew install opam
brew install openexr
brew install openjdk
brew install openjpeg
brew install openssl@1.1
brew install p11-kit
brew install packer
brew install pam_yubico
brew install pango
brew install pcre
brew install pcre2
brew install pcsc-lite
brew install pinentry
brew install pinentry-mac
brew install pixman
brew install pkg-config
brew install poppler
brew install popt
brew install privoxy
brew install pth
brew install pyenv
brew install python@3.8
brew install qt
brew install rabbitmq
brew install rbenv
brew install rbenv-gemset
brew install readline
brew install redis
brew install rsync
brew install ruby-build
brew install sqlite
brew install ssh-copy-id
brew install sshfs
brew install terraform
brew install thrift
brew install tmux
brew install unbound
brew install utf8proc
brew install watchman
brew install webp
brew install wget
brew install wireshark
brew install wxmac
brew install xhyve
brew install xxhash
brew install xz
brew install yarn
brew install ykclient
brew install ykpers
brew install yubico-piv-tool
brew install zlib
brew install zookeeper
brew install zsh
brew install zstd

# https://github.com/Homebrew/homebrew-services
brew tap homebrew/services
brew tap caskroom/fonts
brew tap golemfactory/golem

brew install homebrew/cask/docker
brew install dropbox
brew install evernote
brew install firefox
brew install golem-mainnet-launcher
brew install google-chrome
brew install iterm2
brew install java
brew install kitematic
brew install mysqlworkbench
brew install ngrok
brew install osxfuse
brew install owasp-zap
brew install postman
brew install slack
brew install spotify
brew install sublime-text
brew install tor-browser
brew install vagrant
brew install wireshark
brew install xquartz
brew install zoom

# Needs osxfuse before install
brew install sshfs

brew cleanup
